growatt:
  account:
  password:
    
logging:
  level:
    de:
      blafoo: DEBUG
    org:
      atmosphere: warn
    
server:
  port: ${PORT:8080}
  
spring:
  cloud:
    openfeign:
      client:
        config:
          growatt-client:
            loggerLevel: BASIC
  jpa:
    defer-datasource-initialization: true
  mustache:
    check-template-location: false
    
vaadin:
  # Launch the default browser when starting the application in development mode
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,de.blafoo.bkw